// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkmophibccjciphglqhx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrbW9waGliY2NqY2lwaGdscWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDEwODQsImV4cCI6MjA2NTQ3NzA4NH0.i05YxmsvTzEiUTz-t060NtcOqy-x6vbDIMHgPve75BA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);